Feature/setup
musharraf-pg/todo-mvc-react pull request #1
Opened 2018-01-04 23:26 UTC by musharraf-pg

2018-01-05 14:24 UTC, trevorwright commented on src/components/App.js
> +const AppTitleStyled = styled.div`
This could be a `header` element

2018-01-05 14:25 UTC, trevorwright commented on src/components/App.js
> +const BodyStyled = styled.div`
Avoid using `Body` as a name here, it becomes confusing with the actual `Body` DOM element.

2018-01-05 14:28 UTC, trevorwright commented on src/components/App.js
> +class App extends Component {
Since you have no dependency here yet on any lifecycle events or state, you should default to a stateless functional component.

```
const App = () => {
    <div>
        ...
    </div>
};
```

2018-01-05 14:29 UTC, trevorwright commented on src/components/Footer.js
> +class Footer extends Component {
Same as above, SFC.

2018-01-05 14:29 UTC, trevorwright commented on src/components/Header.js
> +class Header extends Component {
Same as above

2018-01-05 14:29 UTC, YouGoJoe commented on src/components/Footer.js
> +class Footer extends Component {
(**Note:** This comment applies to Header/ToDoItem/ToDoList as well, but thinking about future functionality of the latter two, you may not want to convert them.)

So, since this component isn't "doing anything", it doesn't have to be a full-on class, it can just be a [pure component](https://www.fullstackreact.com/30-days-of-react/day-11/). Pure components work like regular React components that are built with classes when you use them in other parts of your app, they just look simpler and are easier to maintain. The pure component equivalent of this `Footer` is
```
const Footer = () => (<div>Footer</div>);
export default Footer;
```

I won't go through all the ES6 mechanics being invoked there, but the important React thing happening is that you are returning JSX. If your components don't need to do any work with internal state for instance, these components are much cleaner.

They also get passed props as an argument, so if you wanted to dynamically set this `Footer`'s content with a prop called `footerText` it could look like:
```
const Footer = ({ footerText }) => (<div>{footerText}</div>);
export default Footer;
```

and invoking it would look like `<Footer footerText="My footer text" />`

2018-01-05 14:29 UTC, trevorwright commented on src/components/ToDoItem.js
> +class ToDoItem extends Component {
Same as above

2018-01-05 14:29 UTC, trevorwright commented on src/components/ToDoList.js
> +class ToDoList extends Component {
Same as above

2018-01-05 14:30 UTC, trevorwright commented on src/components/App.js
> +
Watch your unnecessary white space :)

2018-01-05 14:30 UTC, trevorwright requested changes
This looks good, small comments. Also you should add package-lock.json to your .gitignore file so that its not used 👍

2018-01-06 14:58 UTC, trevorwright approved these changes
You still have a package-lock included in the PR, you should get rid of that before merging. This looks good, but please avoid adding more work after you've sent a PR.

2018-01-08 15:30 UTC, merged